### ISSUE TITLE
Optional Sculk Sensor Tendril Model animation

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#10]
@AViewFromTheTop can we can we can we can we

ok basically we'd just copy the warden's tendril code
we could also use modmenu's configs for once

**Comment by AViewFromTheTop** [comment]
yeah go ahead do it

**Comment by AViewFromTheTop** [comment]
WHOA WTH IS MY ICON

**Comment by BluePhoenixLOL** [comment]
> WHOA WTH IS MY ICON

?

**Comment by MerpisMe** [comment]
> WHOA WTH IS MY ICON

looks normal to me

**Comment by AViewFromTheTop** [comment]
> we could also use modmenu's configs for once

dont know what that is or how to use it

**Comment by MerpisMe** [comment]
> yeah go ahead do it

i need like. a lot of help. for it.

**Comment by AViewFromTheTop** [comment]
> > yeah go ahead do it
> 
> i need like. a lot of help. for it.

yeah do it

**Comment by MerpisMe** [comment]
> > we could also use modmenu's configs for once
> 
> dont know what that is or how to use it

mod that gives fabric a mod menu with configuration menus

**Comment by MerpisMe** [comment]
> > > yeah go ahead do it
> > 
> > 
> > i need like. a lot of help. for it.
> 
> yeah do it

i'm not a programmer i don't even know how to start wtf is a mixin

**Comment by AViewFromTheTop** [comment]
> > > > yeah go ahead do it
> > > 
> > > 
> > > i need like. a lot of help. for it.
> > 
> > 
> > yeah do it
> 
> i'm not a programmer i don't even know how to start wtf is a mixin

go find out

**Comment by MerpisMe** [comment]
> > > > > yeah go ahead do it
> > > > 
> > > > 
> > > > i need like. a lot of help. for it.
> > > 
> > > 
> > > yeah do it
> > 
> > 
> > i'm not a programmer i don't even know how to start wtf is a mixin
> 
> go find out

heartbroken

**Comment by AViewFromTheTop** [comment]
> heartbroken

man now i feel bad

**Comment by MerpisMe** [comment]
> > heartbroken
> 
> man now i feel bad

manipulation at its finest my dude 
![image](https://user-images.githubusercontent.com/27739930/164951062-23411206-5f94-4aba-8f9f-82b94b381829.png)

**Comment by AViewFromTheTop** [comment]
> > > heartbroken
> > 
> > 
> > man now i feel bad
> 
> manipulation at its finest my dude ![image](https://user-images.githubusercontent.com/27739930/164951062-23411206-5f94-4aba-8f9f-82b94b381829.png)

jk

**Comment by MerpisMe** [comment]
> > > > heartbroken
> > > 
> > > 
> > > man now i feel bad
> > 
> > 
> > manipulation at its finest my dude ![image](https://user-images.githubusercontent.com/27739930/164951062-23411206-5f94-4aba-8f9f-82b94b381829.png)
> 
> jk

yeah i know i was gonna get treetrain to set it up for me anyway

**Comment by AViewFromTheTop** [comment]
> yeah i know i was gonna get treetrain to set it up for me anyway

bruh ive been trying to and here's the issue: ModelPart modelPart = ctx.getLayerModelPart();
how the heck do i just create a blockentitymodellayer

**Comment by MerpisMe** [comment]
> bruh ive been trying to and here's the issue: ModelPart modelPart = ctx.getLayerModelPart(); how the heck do i just create a blockentitymodellayer

look into how bells do it, since i know they use a block model for their base and an entity model for their bell
otherwise idk
