### ISSUE TITLE
Presence Footsteps compat.

### ISSUE THREAD

**Issue by iiinhoj** [Soro335/WilderWild#101]
Some blocks do not make the proper footstep sounds with the [Presence Footsteps](https://modrinth.com/mod/presence-footsteps) mod active.

Some blocks I've identified:
- Hollowed logs
- Sculk blocks
- Echo glass
- Null block

You can map blocks with sounds within the Wilder Wild's internal resource pack (info: https://github.com/Sollace/Presence-Footsteps/wiki/Information-for-Resourcepack-Creators)

**Comment by BluePhoenixLOL** [comment]
oh i use this mod and i didnt notice, thank you.

**Comment by MerpisMe** [comment]
done, thanks for the report!
