### ISSUE TITLE
Game crashes when not launching from IntelliJ

### ISSUE THREAD

**Issue by Treetrain1** [Soro335/WilderWild#12]
no clue what is causing it

using fabric api 0.51.2 and loader 0.14.2

https://pastebin.com/raw/LKe43LkF

POSSIBLE CAUSES: 
- Developer Camera being only accessible when in developer environment
- Almost everything is registered via initializer (sculk_thing = register(a, b, c)) instead of inside the proper singular method that is supposed to register everything

**Comment by Albertsmods** [comment]
That happened to me when I didn't register something correctly, I don't know why it works when you launch it from IntelliJ though

**Comment by FrogPlayzz** [comment]
Yeah, when this fix
I want play it

**Comment by MerpisMe** [comment]
> Yeah, when this fix? I want play it

Stop, we'll get to it whenever we can figure out what's causing it

**Comment by MerpisMe** [comment]
> when fix 💀

i will turn you into soup

**Comment by StancuAlin2008** [comment]
> > when fix 💀
> 
> i will turn you into soup
oh dayum

**Comment by AViewFromTheTop** [comment]
why this happen fix

**Comment by MerpisMe** [comment]
> why this happen fix

idk but the good thing is that it keeps random people from playing the mod while it's in development, so that's a plus :P

**Comment by AViewFromTheTop** [comment]
> idk but the good thing is that it keeps random people from playing with the mod while it's in development, so that's a plus :P

that means we cant get feedback

**Comment by FrogPlayzz** [comment]
i can't play it anyway but i would

**Comment by MerpisMe** [comment]
> > idk but the good thing is that it keeps random people from playing with the mod while it's in development, so that's a plus :P
> 
> that means we cant get feedback

we don't need in depth feedback because we're still working on the mod lol
we already get enough feedback through posting sneak peeks

**Comment by MerpisMe** [comment]
> i can't play it anyway but i would

we get it go away

**Comment by FrogPlayzz** [comment]
I want old tendril animation bruh :CCC

**Comment by MerpisMe** [comment]
> I want old tendril animation bruh :CCC

STOP, i'm serious. even if you did have access you wouldn't be able to have the old tendril animation because
A) it's disabled by default
B) it's unfinished
C) it's laggy as hell

do NOT use this repository as a loophole through your ban from our discord server.

**Comment by FrogPlayzz** [comment]
when will the main member return?

**Comment by AViewFromTheTop** [comment]
whos that

**Comment by MerpisMe** [comment]
> whos that

you lol

he got the wrong idea because i said "we're not bothering him about it" regarding wilderwild when we first started development

this kid's really goddamn annoying and he did this exact same garbage on our discord server, hence why he's banned. trying to figure out how to ban people from github repositories.

**Comment by AViewFromTheTop** [comment]
> > whos that
> 
> you lol

bruh im not the main member isnt that liuk

also you wont believe the anxiety i was feeling with that. My mind was racing at the fact that was the only comment you deleted, and I thought everyone was trying to hide some "supreme overlord" from me that's planning to take me down.

jesus christ why do i think like that

**Comment by MerpisMe** [comment]
> bruh im not the main member isnt that liuk

yeah it is but he also hasn't been active for months :trollface: 

> also you wont believe the anxiety i was feeling with that. My mind was racing at the fact that was the only comment you deleted, and I thought everyone was trying to hide some "supreme overlord" from me that's planning to take me down.
> 
> jesus christ why do i think like that

no no no, i just deleted it because i didn't want you getting the wrong idea about it. i'd mentioned that you were one of the main coders of the larger features for twm and he interpreted that as you being "the main member" or whatever lol

sorry about all of that, i didn't really explain anything

**Comment by StancuAlin2008** [comment]
just a question: after what you said is this issue still a bug or is it WAI (works as intended)

**Comment by MerpisMe** [comment]
> just a question: after what you said is this issue still a bug or is it WAI (works as intended)

it's a bug but we're not concerned about it for now since nobody else should even really know about this repository
