### ISSUE TITLE
Go vote for this issue ❤️ 

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#14]
https://bugs.mojang.com/browse/MC-250692

:)

**Comment by AViewFromTheTop** [comment]
no + L + ratio + touch calcite + mario

**Comment by MerpisMe** [comment]
> no + L + ratio + touch calcite + mario

sobbing

**Comment by AViewFromTheTop** [comment]
> sobbing

i cant believe that mario made you cry

**Comment by MerpisMe** [comment]
> i cant believe that mario made you cry

mario can be a foul man

**Comment by BluePhoenixLOL** [comment]
![image](https://user-images.githubusercontent.com/80720298/165400249-960d8e96-3a96-484e-88a5-3aa05a0043e4.png)

**Comment by BluePhoenixLOL** [comment]
why?

**Comment by BluePhoenixLOL** [comment]
why reopen

**Comment by MerpisMe** [comment]
> ![image](https://user-images.githubusercontent.com/80720298/165400249-960d8e96-3a96-484e-88a5-3aa05a0043e4.png)

that doesn't mean it'll be fixed soon. if we get more people to vote for it, they'll likely fix it sooner

**Comment by Osmiooo** [comment]
> why?

Why not

**Comment by MerpisMe** [comment]
also,

uwu

**Comment by BluePhoenixLOL** [comment]
> > ![image](https://user-images.githubusercontent.com/80720298/165400249-960d8e96-3a96-484e-88a5-3aa05a0043e4.png)
> 
> that doesn't mean it'll be fixed soon. if we get more people to vote for it, they'll likely fix it sooner

ah, so many people look at this github yes

**Comment by Osmiooo** [comment]
> > ![image](https://user-images.githubusercontent.com/80720298/165400249-960d8e96-3a96-484e-88a5-3aa05a0043e4.png)
> 
> that doesn't mean it'll be fixed soon. if we get more people to vote for it, they'll likely fix it sooner

I would like to upvote it aswell but my password is in my pc and as u know I don't have it so I can't connect, I'll try to reset it tomorrow

**Comment by BluePhoenixLOL** [comment]
im kidding dont kill me

**Comment by MerpisMe** [comment]
> im kidding dont kill me

lock your windows and your doors and tear down your walls seal your drains board up the chimney

**Comment by BluePhoenixLOL** [comment]
> > im kidding dont kill me
> 
> lock your windows and your doors and tear down your walls seal your drains board up the chimney

i dont have a chimney

**Comment by Osmiooo** [comment]
> > im kidding dont kill me
> 
> lock your windows and your doors and tear down your walls seal your drains board up the chimney

That's a lot of things to do

**Comment by MerpisMe** [comment]
> i dont have a chimney

you do now uwu

**Comment by Osmiooo** [comment]
> > i dont have a chimney
> 
> you do now uwu

That's nice of you to build him a chimney

**Comment by MerpisMe** [comment]
> That's nice of you to build him a chimney

board it up

**Comment by BluePhoenixLOL** [comment]
> Collaborator

where is it?

**Comment by Osmiooo** [comment]
> 

Probably somewhere

**Comment by BluePhoenixLOL** [comment]
> > That's nice of you to build him a chimney
> 
> board it up
![hey_merp](https://user-images.githubusercontent.com/80720298/165413555-28553d14-b92c-4790-a328-42a718b3b0ce.png)
oh hey merp

**Comment by BluePhoenixLOL** [comment]
![NOOOO_merp](https://user-images.githubusercontent.com/80720298/165413637-32cf02fa-ea00-49f5-8577-a77a3446b39f.png)
NOOOOOOOOOOOOO MERPPPPPPPPPP NOOOOOO

**Comment by AViewFromTheTop** [comment]
> also,
> 
> uwu

i will deglove you

**Comment by MerpisMe** [comment]
> > also,
> > uwu
> 
> i will deglove you

too late

**Comment by AViewFromTheTop** [comment]
> > > also,
> > > uwu
> > 
> > 
> > i will deglove you
> 
> too late

You have hands still. It isn't too late.

**Comment by AViewFromTheTop** [comment]
> EDIT: i have paws

if you say that one more time, ANYTHING related to furries, be it a joke or not, I will add the "Merp Is A Furry Block" to Minecraft.

**Comment by AViewFromTheTop** [comment]
> do i?
> 
> EDIT: ~i have paws :trollface:~ (joke, i am not a furry)

please stop referencing furries

**Comment by BluePhoenixLOL** [comment]
> LMAO WHY THE HELL IS HENRIK ASSIGNED TO THE BUG WHY IS HE OF ALL PEOPLE FIXING A FREAKING MUD BLOCK MODEL

he doesnt JUST do worldgen and stuff

**Comment by AViewFromTheTop** [comment]
> > LMAO WHY THE HELL IS HENRIK ASSIGNED TO THE BUG WHY IS HE OF ALL PEOPLE FIXING A FREAKING MUD BLOCK MODEL
> 
> he doesnt JUST do worldgen and stuff

read my edit
also im pretty sure henrik did the allay alongside ulraf as well, ik he doesn't just to worldgen

**Comment by AViewFromTheTop** [comment]
> LMAO WHY THE HELL IS HENRIK ASSIGNED TO THE BUG WHY IS HE OF ALL PEOPLE FIXING A FREAKING MUD BLOCK MODEL ITS LITERALLY ONE LINE IN A JSON FILE AND THEY PULL OUT THE SECOND BEST DEVELOPER IN ALL OF SWEDEN TO FIX IT

Also yes, in case you're wondering, Henrik actually is the second best developer in all of Sweden. That's mostly what makes the fact he's working on Minecraft so hilarious, and especially the fact he's tasked with slightly altering one line in a .json file of all things.
