### ISSUE TITLE
Sculk Echoer Pillar Feedback

### ISSUE THREAD

**Issue by AViewFromTheTop** [Soro335/WilderWild#19]
- Wider patches with greater falloff (that is, bones should get shorter as they get further from the sampled noise region)
- Pillars should not generate quite as close to one another to give spines room to grow outward (minimum 2 blocks' distance between each one)
- Stuff spawning on them (especially the hanging ones) should be far less common
- Sculk should replace (at minimum) the base block but should be able to replace up to a max of 4 blocks
- Generally just a little bit less messy

**Comment by StancuAlin2008** [comment]
Issue #12 still exists so uhh could u send some pictures

**Comment by MerpisMe** [comment]
> Issue #12 still exists so uhh could u send some pictures

i actually think it's caused by the panorama camera, since it also crashes if you run the game through intellij outside of the developer environment

**Comment by MerpisMe** [comment]
> If it isn't that, it's 100% because almost everything is registered via initializer (sculk_thing = register(a, b, c)) instead of inside the proper singular method that is supposed to register everything, but idk

that wouldnt really explain why it only crashes outside of the developer environment though
