### ISSUE TITLE
Ancient Goat Horn unique interactions

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#20]
- **Sensor**: gets put into "hiccup mode" wherein it activates at random, playing a hiccup sound (good for compact rng machines); however, if activated by an entity and a warden is nearby, causes the warden to immediately become aggravated with that entity

- **Shrieker**: Will Summon the Warden immediately. On non-worldgen Shriekers, they will lose a soul and be unable to spawn new Wardens or shriek once they've reached 0.

- **Echoer**: spits echoing bubbles in random directions for a few seconds, which can be used to distract the warden, but in turn causes the echoer to break afterward. if the echoer in question is upside down, after spewing bubbles, it falls and breaks (without dropping anything)

- **Catalyst**: Will generate a worldgen Sculk Patch and break afterwards. (May not be possible.)

- **Hanging Tendril**: explodes (because that'd be funny lol)

- **Warden**: The Warden will take notice of the player if hit, but not receive any damage. The horn is a puzzle piece to avoiding the Warden, so using it on different Sculk Blocks strategically will be more effective.

**Comment by MerpisMe** [comment]
these took me like 30 minutes to come up with lol

**Comment by AViewFromTheTop** [comment]
Ok merp at this point we might as well just try to find a way to cancel the registration of Sensors and Shriekers and make our own versions of them, considering how much we want to do with them PLUS this

**Comment by MerpisMe** [comment]
> Ok merp at this point we might as well just try to find a way to cancel the registration of Sensors and Shriekers and make our own versions of them, considering how much we want to do with them PLUS this

yeah probably. we could also probably just use a mixin and just slap the existing code plus our code on top (optifine style)

**Comment by AViewFromTheTop** [comment]
> yeah probably. we could also probably just use a mixin and just slap the existing code plus our code on top (optifine style)

Simply impossible- with how much we want to change, Mixins won't suffice.

**Comment by MerpisMe** [comment]
> > yeah probably. we could also probably just use a mixin and just slap the existing code plus our code on top (optifine style)
> 
> Simply impossible- with how much we want to change, Mixins won't suffice.

frick
well at the very least, if we can figure out how to cancel the registries, we should keep most if not all of the vanilla code and simply add to it

**Comment by BluePhoenixLOL** [comment]
whats Ancient Goat Horn

**Comment by AViewFromTheTop** [comment]
> whats Ancient Goat Horn

use it in-game youll see

**Comment by MerpisMe** [comment]
> Not too sure on this, the durability mechanic wouldn't make much sense, and it would be terrible if naturally generating Shriekers could loose their souls. However, if loosing souls only applied to new Shriekers, that'd help balance it out a bit more. One Warden summon, one soul lost.

yeah that second part was pretty much what i meant, didn't make that very clear

> Two issues:
> 
> 1. This would encourage players to attack the Warden, as it reacts to it. I think that making the Warden ignore the sounds would be best, as it doesn't give anyone a reason to try to attack the Warden to see its reaction, and it also makes sense in the fact that the horn was taken over by Sculk; the Warden won't necessarily know it's a player making the sound anyway. On top of this, sounds shouldn't really be able to hurt the Warden to begin with, it introduces a strange contrast in my opinion.

fair enough

> 2. The way Sonic Booms were implemented is that it can ONLY be used on the entity the Warden roared at- nothing else. It would be quite challenging to work around this, and if we do find a way, then that introduces the issue that players can easily distract the Warden from other players.

oh, okay, true, i didn't consider the fact that you could use it to distract the warden.

> I think it's more rewarding to use the Horn as a "puzzle piece" to avoid the Warden with. You use it on different Sculk Blocks and see which one helps more, and try to distract it that way. It's loot FOUND in Ancient Cities, meaning players will already have to be avoiding Sculk and possibly the Warden for a bit before they get it.

admittedly, the warden was the last thing i added to this list, so it's the least thought-out one of the bunch. but i do agree with you, it probably shouldn't be used as an attack against the warden

**Comment by MerpisMe** [comment]
> I suggest you make the sculk echoer crack instead of instantly being destroyed the first time you use the ancient goat horn and if you do it the second time it would break

i mean, what it does is pretty overpowered as is. it shoots out bubbles in random directions that completely distract the warden for the entire duration, so i think it's pretty fair that it self destructs afterward

**Comment by StancuAlin2008** [comment]
yea but maybe shoot less bubbles that only distract the warden the warden when they pop? cuz this way it's basically like a snowball but lasts a little bit longer so you can make your escape while the warden is busy investigating the bubbles

**Comment by MerpisMe** [comment]
> yea but maybe shoot less bubbles that only distract the warden the warden when they pop? cuz this way it's basically like a snowball but lasts a little bit longer so you can make your escape while the warden is busy investigating the bubbles

they're meant to distract the warden when they pop, we're planning on making echoers emit echoing bubble particles when activated, which then pop and send the vibration on

in any case, i still don't really see why it shouldn't break after one time. echoers are pretty easy to get at the moment anyway

**Comment by StancuAlin2008** [comment]
imo it shouldn't break after one time cuz it could techinically help the warden hear you still

**Comment by MerpisMe** [comment]
> imo it shouldn't break after one time cuz it could techinically help the warden hear you still

eh. fair enough i guess.

**Comment by MerpisMe** [comment]
> Darkness doesn't have any effects on entity's AI, it's only meant for the player

which was why i added slowness to it

> Either way this would entirely defeat the purpose of Slowness Arrows/Potions, I don't think this should be implemented. I think the fact that the projectile won't be effected by gravity is enough on its own, considering how frustrating Crossbows and Bows are to use.

that's true, but if possible i'd like it to have some effect on entities attacked with it since i'm kind of liking the idea of using it as a sort of "recovery".

maybe instead, crouching whilst using it could cause it to blow nearby mobs away, similar to the wind horn in dungeons?

**Comment by AViewFromTheTop** [comment]
> that's true, but if possible i'd like it to have some effect on entities attacked with it since i'm kind of liking the idea of using it as a sort of "recovery".
> 
> maybe instead, crouching whilst using it could cause it to blow nearby mobs away, similar to the wind horn in dungeons?

I don't agree with it honestly, it shouldn't be too overpowered. It should be a unique weapon that has fun mechanics with Sculk, but not something you can do stuff like THAT with. In terms of a recovery weapon, I'm just not feeling it. It entirely defeats the purpose of tipped arrows, and makes an already unique and powerful weapon even more unique.

**Comment by MerpisMe** [comment]
> I don't agree with it honestly, it shouldn't be too overpowered. It should be a unique weapon that has fun mechanics with Sculk, but not something you can do stuff like THAT with. In terms of a recovery weapon, I'm just not feeling it. It entirely defeats the purpose of tipped arrows, and makes an already unique and powerful weapon even more unique in a bad way.

fair enough (i say that too often)

**Comment by AViewFromTheTop** [comment]
> fair enough (i say that too often)

BTW did you read my edit about the PVZGW mechanics that'd be able to balance out this weapon?
Idk why I'm good at weapon balancing, but I am. Don't ask.

**Comment by AViewFromTheTop** [comment]
i also must say, it's hilarious that what started out as a typical annoying vine boom joke turned into something that's being taken seriously and actually would be fun to play with

**Comment by MerpisMe** [comment]
> i also must say, it's hilarious that what started out as a typical annoying vine boom joke turned into something that's being taken seriously and actually would be fun to play with

i didn't hear the sound until i played with it for myself for the first time last night and it scared the shit out of me
i will hold this against you

**Comment by MerpisMe** [comment]
> why what happened

LOUD

**Comment by BluePhoenixLOL** [comment]
it should go through blocks

**Comment by AViewFromTheTop** [comment]
> it should go through blocks

It goes through Glass, Sculk, and Osseous Sculk at the moment

**Comment by AViewFromTheTop** [comment]
Shrieker and Sensor interactions have been added.

**Comment by AViewFromTheTop** [comment]
> Shrieker and Sensor interactions have been added.

The Sensor hiccups too often.

**Comment by AViewFromTheTop** [comment]
@MerpisMe I seriously think the Catalyst one is too overpowered. Considering this is a giant _vibration_, why don't we leave out the Sculk Jaw and Catalyst?

**Comment by Soro335** [comment]
@AViewFromTheTop another little bu

https://user-images.githubusercontent.com/82042293/166122133-dc0a542c-d326-4ae3-ab49-0ccfb334dd76.mp4
