### ISSUE TITLE
Sculk Echoers send vibrations back to the same sensor

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#23]
Sculk Sensors send a vibration to a sculk echoer, which then send the vibration back (as a result of the bubbles)
If possible, we probably want to make sculk sensors not receive vibrations from a block that they just activated

**Comment by AViewFromTheTop** [comment]
> Sculk Sensors send a vibration to a sculk echoer, which then send the vibration back (as a result of the bubbles) If possible, we probably want to make sculk sensors not receive vibrations from a block that they just activated

Cooldown just needs to be increased.

**Comment by AViewFromTheTop** [comment]
not sure how to fix this honestly

**Comment by AViewFromTheTop** [comment]
> not sure how to fix this honestly

ACTUALLY, we could make a separate GameEvent that doesn't activate Sensors, and use that Big Bubble idea. Only the first bubble (big bubble) could set off sensors.

**Comment by AViewFromTheTop** [comment]
@MerpisMe could you test with the latest commit?

**Comment by Soro335** [comment]
remove integrations with naturally generated sculk shrieker

**Comment by MerpisMe** [comment]
> remove integrations with naturally generated sculk shrieker

why

**Comment by MerpisMe** [comment]
> @MerpisMe could you test with the latest commit?

it crashes

**Comment by Soro335** [comment]
> > remove integrations with naturally generated sculk shrieker
> 
> why

it works too weird, test it

**Comment by AViewFromTheTop** [comment]
> > @MerpisMe could you test with the latest commit?
> 
> it crashes

try again, I changed the nbt

**Comment by AViewFromTheTop** [comment]
> it works too weird, test it

I limited both worldgen and non-worldgen shriekers to only two wardens with the horn

**Comment by Soro335** [comment]
https://user-images.githubusercontent.com/82042293/166110951-c4ac8dbe-1ff8-49b8-8408-d67cc2c4a44d.mp4

**Comment by AViewFromTheTop** [comment]
> 2022-04-30_18-02-50.mp4

WHOA HOW DID YOU GET THE TEXTURES TO SHOW UP PROPERLY

**Comment by AViewFromTheTop** [comment]
YOOOOOOOOOO THE TEXTURES ARE SUDDENLY WORKING

**Comment by AViewFromTheTop** [comment]
@Soro335 the solution to that is just to make separate blocks sadly, MC doesn't let you save BlockStates when you break blocks

**Comment by Soro335** [comment]
> @Soro335 the solution to that is just to make separate blocks sadly, MC doesn't let you save BlockStates when you break blocks

if this is the only solution - yes, make a separate block

**Comment by AViewFromTheTop** [comment]
> if this is the only solution - yes, make a separate block

I was JUST about to commit the new block, but I found out you can do it through loot tables with less than half the effort. I'm dumb.

**Comment by AViewFromTheTop** [comment]
I simply can't recreate this anymore after a few hours of testing, closing the issue.
