### ISSUE TITLE
Echo Glass

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#24]
- made with 2 tinted glass and an echo shard (shapeless)
- blocks sonic boom attack, but cracks each time
- exposure to light levels greater than 7 (daylight and blocklight) causes it to slowly crack
- repairs itself slowly in the dark
- placing it makes vibrations no matter what (not affected by wool occlusion)

**Comment by AViewFromTheTop** [comment]
Echo Shards are gonna need to be a lot more common if you guys want this to even be remotely usable

**Comment by MerpisMe** [comment]
> Echo Shards are gonna need to be a lot more common if you guys want this to even be remotely usable

the point is to make it difficult to amass large quantities of since it's pretty powerful

**Comment by AViewFromTheTop** [comment]
> the point is to make it difficult to amass large quantities of since it's pretty powerful

The fact that it cracks kinda ruins its purpose then, if it's not meant to be gained in large quantities.

**Comment by MerpisMe** [comment]
> > the point is to make it difficult to amass large quantities of since it's pretty powerful
> 
> The fact that it cracks kinda ruins its purpose then, if it's not meant to be gained in large quantities. What I think should happen is that it can heal over time, but can still crack.

mm i guess so. it only requires one echo shard to make though. i'll edit this list with some better functionality

**Comment by AViewFromTheTop** [comment]
> * placing it makes vibrations no matter what (not affected by wool occlusion)

I don't like this idea, it's just a "unique" feature for the sake of being unique. Placing Obsidian doesn't do this, nor do even Sculk blocks. It just feels unnecessary and quite pointless in my opinion.

**Comment by MerpisMe** [comment]
> I don't like this idea, it's just a "unique" feature for the sake of being unique. Placing Obsidian doesn't do this, nor do even Sculk blocks. It just feels unnecessary and quite pointless in my opinion.

fair enough
