### ISSUE TITLE
The game will crash if I create another new world

### ISSUE THREAD

**Issue by AxolotlMC12** [Soro335/WilderWild#27]

**Comment by MerpisMe** [comment]
Could you attach a crash log so we can investigate the issue?

**Comment by AViewFromTheTop** [comment]
> Could you attach a crash log so we can investigate the issue?

The Catalysts and Tendrils are likely fighting.

**Comment by AxolotlMC12** [comment]
content://media/external/downloads/16416

**Comment by AxolotlMC12** [comment]
https://drive.google.com/file/d/12CQFnbSJeLCT6QzkAo5izhM0WnSsFwa9/view?usp=drivesdk

**Comment by MerpisMe** [comment]
> https://drive.google.com/file/d/12CQFnbSJeLCT6QzkAo5izhM0WnSsFwa9/view?usp=drivesdk log

it's not set to be viewable by anybody with the link

**Comment by AxolotlMC12** [comment]
Copy and paste

**Comment by AxolotlMC12** [comment]
In google

**Comment by MerpisMe** [comment]
it's not working; you could just click and drag the crash log file onto the comment box and it should work that way

**Comment by AxolotlMC12** [comment]
[2022-05-02-2.log (1).txt](https://github.com/Soro335/WilderWild/files/8604182/2022-05-02-2.log.1.txt)

**Comment by AxolotlMC12** [comment]
work?

**Comment by MerpisMe** [comment]
> work?

yea it works, but i'm still not really sure what's causing it

**Comment by AViewFromTheTop** [comment]
@MerpisMe @Soro335 I'm pretty sure this is because of the Fungus decorator, but I could be wrong. The blockstate was allowed to set with a value of 0 while the minimum is 1, so i'm testing it now.
