### ISSUE TITLE
New mod name ideas(Because i found another mod with this name)

### ISSUE THREAD

**Issue by Soro335** [Soro335/WilderWild#28]
![image](https://user-images.githubusercontent.com/82042293/166324406-602893e2-e113-4871-92d8-6e826fa845e4.png)

**Comment by AViewFromTheTop** [comment]
oh for gods sake another freaking 1.16.5 mod
java 17 better + l + ratio

**Comment by AxolotlMC12** [comment]
TheWilderMod

**Comment by AxolotlMC12** [comment]
TheWildUpdate+

**Comment by AxolotlMC12** [comment]
BetterWildUpdate

**Comment by BluePhoenixLOL** [comment]
WildUpgrade

**Comment by Treetrain1** [comment]
The Wilder Mod

lol twm

**Comment by MerpisMe** [comment]
> The Wilder Mod
> 
> lol twm

no

**Comment by Osmiooo** [comment]
Didn't we already established to keep Wilder Wild because it's not the same name and other things?

**Comment by MerpisMe** [comment]
> Didn't we already established to keep Wilder Wild because it's not the same name and other things?

mmm idk maybe

**Comment by Treetrain1** [comment]
> Didn't we already established to keep Wilder Wild because it's not the same name and other things?

Wilder Wild is a good name but I have random bad ideas

Absolutely Wild
Wild Wild
Wild Plus
Wilderness Plus
Crazy Wild
The Wild Update Plus
Absolutely Wild Mod

idk probably should keep Wilder Wild though

**Comment by Osmiooo** [comment]
> > Didn't we already established to keep Wilder Wild because it's not the same name and other things?
> 
> Wilder Wild is a good name but I have random bad ideas
> 
> Absolutely Wild Wild Wild Wild Plus Wilderness Plus Crazy Wild The Wild Update Plus Absolutely Wild Mod
> 
> idk probably should keep Wilder Wild though

I thought of "Wild". Just Wild.

**Comment by MerpisMe** [comment]
#wiggerwednesday or #waluigiwednesday

**Comment by MerpisMe** [comment]
closing for now. we'll worry about it if curseforge complains about it
