### ISSUE TITLE
Ancient Horn Projectile uses incorrect model pivot

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#30]
the ancient horn projectile uses an incorrectly placed pivot, which causes the plane to be displaced outward. i personally find this to be extremely misleading as it makes the projectile appear above the hitbox in most cases, which can lead to missed shots

basically i just want the model and pivot to be located at 0,0

i could work on fixing this when i get home later today, but i'm adding you (avftt) as an assignee in case you wanna give it a shot while i'm at work

**Comment by AViewFromTheTop** [comment]
no

**Comment by AViewFromTheTop** [comment]
also the projectile is supposed to be pointed slightly upwards for easier viewing

but yeah ik the pivot's probably screwed up, i'm not gonna mess with it because i went insane trying to fix it last time

**Comment by MerpisMe** [comment]
> but yeah ik the pivot's probably screwed up, i'm not gonna mess with it because i went insane trying to fix it last time

that's where i come in  :)

i hate myself
