### ISSUE TITLE
Upside-Down Echoers Should Sometimes Generate On Ceiling Pillars

### ISSUE THREAD

**Issue by AViewFromTheTop** [Soro335/WilderWild#5]
Here's why:
The entire point of those pillars gameplay-wise is to encourage the player to build upwards, taking the risk of setting off a Shrieker.
Pillars are MUCH more common on ceilings. Since they're on ceilings, they're much harder to reach than the normal pillars, therefore reinforcing the idea of building up.

**Comment by MerpisMe** [comment]
mmm okay, fine. i just want them to he able to be placed on the ceiling and on the floor, no walls
