### ISSUE TITLE
Things we need to finish before the first release:

### ISSUE THREAD

**Issue by Soro335** [Soro335/WilderWild#6]
Birch forest:
- [x] Add fallen birch logs gen
- [x] Remade vanila birch tress and add them to gen
- [x] Add better grass pathes into birch forest
- [x] Add mushrooms for trees

Deep Dark:
- [x] Fix veins placement
- [x] Other fixes

Other:
- [x] Cattail should generate in mangrove swamps
- [x] New flowers should work in composter 
- [x] Add flowered lily pads
- [x] idk

**Comment by AViewFromTheTop** [comment]
@Soro335 what exactly needs to be removed from which biome
