### ISSUE TITLE
Beta beaches?

### ISSUE THREAD

**Issue by Soro335** [Soro335/WilderWild#74]
I remember when Henrik tried to bring back the old beaches in 1.18 but it wasn't added, I think it will look cool in our mod
![image](https://user-images.githubusercontent.com/82042293/183071487-d6575f68-b66f-48c9-b0d6-abde909898a0.png)
![image](https://user-images.githubusercontent.com/82042293/183071546-8b1549af-7fad-45f5-a914-e16db5123b9d.png)

**Comment by Soro335** [comment]
> i can't go on planetminecraft for some reason can someone send me that datapack

https://github.com/Crystalis7/Hybrid-Beta/tree/master/Hybrid%20Beta%201.19 

I forgot about this

**Comment by MerpisMe** [comment]
bump, would love to see this in the mod

**Comment by Soro335** [comment]
ohhhhh, nether have something like beaches from beta 
![2022-08-16_21 55 52](https://user-images.githubusercontent.com/82042293/184960325-c6378f0c-1565-4c2a-81fc-3092661cc091.png)

![2022-08-16_21 59 09](https://user-images.githubusercontent.com/82042293/184960288-de7151a3-b7e6-48fc-8b99-52492187bab6.png)

**Comment by Soro335** [comment]
> bump, would love to see this in the mod

this datapack + wilder wild 

![2022-08-16_14 22 07](https://user-images.githubusercontent.com/82042293/184960989-1469a6ee-a805-48f2-904e-ce968527dce1.png)
![2022-08-16_14 16 23](https://user-images.githubusercontent.com/82042293/184961044-5a392c8e-0634-446b-a99b-25be0b1cfae8.png)
