### ISSUE TITLE
Firefly Lanterns

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#81]
Surround a firefly bottle with iron nuggets to make a firefly lantern!

- has a unique model & texture made to show the firefly inside, which uses a block entity renderer to render a quaternion that moves around using sin/cos functions
- acts like a regular lantern but emits far less light
- you can add up to four fireflies to a single lantern by clicking on it with a firefly bottle, which will increase the amount of light produced
- you can remove fireflies by right clicking with an empty bottle

0 fireflies = light level 0
1 firefly = light level 3
2 fireflies = light level 6
3 fireflies = light level 9
4 fireflies = light level 12

**Comment by AViewFromTheTop** [comment]
Can you make the model and texture for it real quick

**Comment by MerpisMe** [comment]
> Can you make the model and texture for it real quick

yea

**Comment by MerpisMe** [comment]
https://github.com/Soro335/WilderWild/tree/FireflyLanterns @AViewFromTheTop

**Comment by AViewFromTheTop** [comment]
is the current iteration good enough because idk how else to improve it

**Comment by MerpisMe** [comment]
> is the current iteration good enough because idk how else to improve it

yeah i think it's perfect,
though make it start off with one firefly when placed via the item if it doesn't already

**Comment by AViewFromTheTop** [comment]
> > is the current iteration good enough because idk how else to improve it
> 
> yeah i think it's perfect, though make it start off with one firefly when placed via the item if it doesn't already

that'd lead to a firefly dupe

**Comment by MerpisMe** [comment]
> > > is the current iteration good enough because idk how else to improve it
> > 
> > 
> > yeah i think it's perfect, though make it start off with one firefly when placed via the item if it doesn't already
> 
> that'd lead to a firefly dupe

you have to use a firefly bottle to craft a firefly lantern so no not really

**Comment by MerpisMe** [comment]
speaking of which, does crafting a firefly lantern retain the colour of the firefly used to craft it?

i think maybe we should just change the recipe to an empty glass bottle surrounded by iron nuggets and make the texture not display a firefly, then make it start with 0 by default, since then that would basically solve all of these issues
we might have to rename it to like "glass lantern" or something in that case

**Comment by AViewFromTheTop** [comment]
> speaking of which, does crafting a firefly lantern retain the colour of the firefly used to craft it?
> 
> i think maybe we should just change the recipe to an empty glass bottle surrounded by iron nuggets and make the texture not display a firefly, then make it start with 0 by default, since then that would basically solve all of these issues we might have to rename it to like "glass lantern" or something in that case

Agreed. However, it'd then be too limiting to only let you have Fireflies. I think it could also double as an item display case, a literal Lava Lamp, and maybe a small water tank.

**Comment by AViewFromTheTop** [comment]
Unfortunately I don't think it's possible to craft an item with BlockEntity NBT, so we're quite stuck.

**Comment by MerpisMe** [comment]
> Agreed. However, it'd then be too limiting to only let you have Fireflies. I think it could also double as an item display case, a literal Lava Lamp, and maybe a small water tank.

oh my god OH MY GOD OH MY GOD

**Comment by MerpisMe** [comment]
> > Agreed. However, it'd then be too limiting to only let you have Fireflies. I think it could also double as an item display case, a literal Lava Lamp, and maybe a small water tank.
> 
> oh my god OH MY GOD OH MY GOD

(this means i am absolutely for all of the ideas you listed btw)

**Comment by AViewFromTheTop** [comment]
> > oh my god OH MY GOD OH MY GOD

Hello, Heart Attack! My name is SpongeBob!

> (this means i am absolutely for all of the ideas you listed btw)

ok

**Comment by AViewFromTheTop** [comment]
no honestly i dont like those ideas anymore

**Comment by AViewFromTheTop** [comment]
@MerpisMe should we close this

**Comment by MerpisMe** [comment]
yea
