### ISSUE TITLE
Crash when placing termites

### ISSUE THREAD

**Issue by Osmiooo** [Soro335/WilderWild#82]
I was on a server with multiple mods installed, my friend placed a termite mound and both of our games crashed. We can't relog because the termites keep making our game crash.

Mods installed: Iris, sodium, worldedit, WI Zoom, fabric api and dinocraft (dev version)

Crash report: [crash-2022-08-13_00.27.26-client.txt](https://github.com/Soro335/WilderWild/files/9330152/crash-2022-08-13_00.27.26-client.txt)

**Comment by BluePhoenixLOL** [comment]
ah, i know, remove termites

**Comment by Osmiooo** [comment]
from wilder wild? good idea

**Comment by Treetrain1** [comment]
Just fixed this on Dinocraft's side
The issue was that both mods had the AdvancedMath class in the same package so it was overridden.
