### ISSUE TITLE
Wilder Wild 1.0.1 crashed for no reason 

### ISSUE THREAD

**Issue by Soro335** [Soro335/WilderWild#84]
This error was confirmed by 6 people. 
Everyone has the same reason

https://pastebin.com/kCqdN2c2

**Comment by SuperNolax** [comment]
for me it was exit code -1

**Comment by MerpisMe** [comment]
aaaaaaaaaaaaaaaaaaaaaaa

**Comment by Treetrain1** [comment]
weird

nothing changed in that area between releaes
ill give it a look
