### ISSUE TITLE
SUGGESTION: EXP Bottles force Catalysts to spread sculk

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#87]
yeah that's it pretty much
pretty sure exp bottles drop 1-3 exp, so we can just take whatever value it decides to drop and calculate how much sculk would be spread from it

**Comment by MerpisMe** [comment]
i feel this is just kind of a nice qol change, since while it may not make a whole lot of sense from a lore aspect, it's close enough to be feasible

**Comment by AViewFromTheTop** [comment]
ugh

**Comment by AViewFromTheTop** [comment]
conflicts with lore

**Comment by MerpisMe** [comment]
> conflicts with lore

p

**Comment by AViewFromTheTop** [comment]
> p

?

**Comment by MerpisMe** [comment]
> > p
> 
> ?

i accept defeat
