### ISSUE TITLE
2 ideas

### ISSUE THREAD

**Issue by AViewFromTheTop** [Soro335/WilderWild#9]
- [ ] We should add upsidedown Sculk Sensors because why not
- [ ] If a player-placed Shrieker receives a vibration from an Echoer, it should still be able to summon the Warden. This may be what encourages players to get up and actually grab the Echoers, as Wardens can be very helpful if you use them right.

**Comment by MerpisMe** [comment]
> * [ ]  If a player-placed Shrieker receives a vibration from an Echoer, it should still be able to summon the Warden. This may be what encourages players to get up and actually grab the Echoers, as Wardens can be very helpful if you use them right.

very hard no on this one, HOWEVER, i do think we could make it possible to set a shrieker to can_summon, perhaps via the use of echo shards (surround a shrieker with 8 echo shards in a crafting grid)

**Comment by AViewFromTheTop** [comment]
> very hard no on this one,

aaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by MerpisMe** [comment]
> * [ ]  We should add upsidedown Sculk Sensors because why not

also, if we add upside down sensors then that would make upside down echoers pretty useless. 
maybe we could make a "hanging tendril" that can do the same thing as a sculk sensor but hangs from the ceiling!

**Comment by MerpisMe** [comment]
> > very hard no on this one,
> 
> aaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

i say no because that feels too easy. you'd have to go in, get two things, and then you'd instantly have a warden farm

**Comment by AViewFromTheTop** [comment]
> also, if we add upside down sensors then that would make upside down echoers pretty useless. 

What I was thinking is that the ceiling pillars could rarely have a sensor, so you could send a vibration up there and watch it fly across the ceiling

**Comment by AViewFromTheTop** [comment]
> you'd instantly have a warden farm

oh

**Comment by MerpisMe** [comment]
> > also, if we add upside down sensors then that would make upside down echoers pretty useless.
> 
> What I was thinking is that the ceiling pillars could rarely have a sensor, so you could send a vibration up there and watch it fly across the ceiling

sure but now i really want to do a hanging tendril block because that would be absolutely sick. it could be a vine like block perhaps

**Comment by AViewFromTheTop** [comment]
@MerpisMe would you be able to animate this like the sensor tendrils
![hanging_tendril](https://user-images.githubusercontent.com/87103914/164521846-19face22-e718-4ebf-a426-a770484c2e90.png)

**Comment by AViewFromTheTop** [comment]
![hanging_tendril](https://user-images.githubusercontent.com/87103914/164522210-c678b401-ad2c-419e-b614-4ca33fec9704.png)
@MerpisMe updated

**Comment by MerpisMe** [comment]
> ![hanging_tendril](https://user-images.githubusercontent.com/87103914/164522210-c678b401-ad2c-419e-b614-4ca33fec9704.png)
> @MerpisMe updated

yeah, i'll work on it in a bit
