### ISSUE TITLE
Rotatable Reinforced Deepslate

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#94]
This was originally planned for the initial release but we all totally forgot that we had even discussed about it lol

I think this should be fairly easy to do (just not for me because i'm incompetent)

**Comment by BluePhoenixLOL** [comment]
I only know one way to do this, but it might break compatibility and cause lots of bugs so

**Comment by MerpisMe** [comment]
it's.. literally a mixin and an added blockstate
reinforced deepslate doesn't have any additional code

**Comment by BluePhoenixLOL** [comment]
no, i would have to replace the registry, reinforced deepslate doesn't have its own class, and its different, its only coded in the Blocks class

**Comment by BluePhoenixLOL** [comment]
so i cant just "add a blockstate" as I would still have to do the thing that could break

**Comment by MerpisMe** [comment]
doesnt the blocks class also allow you to set what kind of block it is
like quartz pillars dont have their own class

**Comment by BluePhoenixLOL** [comment]
yes thats the problem, i have to mixin there and change it which could break lots of stuff

**Comment by MerpisMe** [comment]
mmmkay well give it a shot and we'll see if stuff breaks

**Comment by MerpisMe** [comment]
@AViewFromTheTop how do
