### ISSUE TITLE
Mojang's Mappings?

### ISSUE THREAD

**Issue by Treetrain1** [Soro335/WilderWild#95]
@AViewFromTheTop hello this may be important for you

ok heres why we should switch to mojang's mappings

- Names of methods and fields will be a lot more accurate to what they actually do
- No more method_69420() or field_43472
- Allows for an easy Forge port by not having to convert mappings
- We won't have to rely on yarn mappings to update to get good mappings

and no, it doesnt break registries :trollface:  go to the Mojmaps branch and test it lol

**Comment by AViewFromTheTop** [comment]
Look better

**Comment by AViewFromTheTop** [comment]
Loom

**Comment by MerpisMe** [comment]
but why

**Comment by AViewFromTheTop** [comment]
> but why

It’s better

**Comment by MerpisMe** [comment]
> > but why
> 
> It’s better

how so
is it just because you're used to it?

**Comment by MerpisMe** [comment]
being used to it is a valid reason, but if that's the only reason you have then it's not very reasonable

the benefits of mojmaps far outnumber the benefits of loom lol

**Comment by BluePhoenixLOL** [comment]
Yeah

**Comment by MerpisMe** [comment]
@AViewFromTheTop could you please give us a reason why you think loom is better so we can come up with a compromise
if it's because you dont want to relearn the names of methods then maybe we can consider against it, but you have to actually tell us that

**Comment by BluePhoenixLOL** [comment]
@AViewFromTheTop

**Comment by BluePhoenixLOL** [comment]
Say somethin

**Comment by AViewFromTheTop** [comment]
loom saved my life
my arm got sliced in half and loom stitched it

**Comment by BluePhoenixLOL** [comment]
We need a real response. Not just jokes.

**Comment by MerpisMe** [comment]
> loom saved my life my arm got sliced in half and loom stitched it

LMAO what

no but seriously are you joking or do you actually care if we migrate to mojmaps

**Comment by Treetrain1** [comment]
lunade its still loom mappings on mojmaps
![image](https://user-images.githubusercontent.com/39657565/185467385-6e790032-302f-4c93-a645-f567e2d2b011.png)

**Comment by AViewFromTheTop** [comment]
> lunade its still loom mappings on mojmaps ![image](https://user-images.githubusercontent.com/39657565/185467385-6e790032-302f-4c93-a645-f567e2d2b011.png)

no like the current thing i mean

**Comment by BluePhoenixLOL** [comment]
> > no but seriously are you joking or do you actually care if we migrate to mojmaps
> 
> just make a branch of 1.1 for mojmaps i guess last time is used mojmaps i literally couldn't access registries for some reason (though blockpos and all that stuff still worked)

Krill issue

**Comment by MerpisMe** [comment]
> > lunade its still loom mappings on mojmaps ![image](https://user-images.githubusercontent.com/39657565/185467385-6e790032-302f-4c93-a645-f567e2d2b011.png)
> 
> no like the current thing i mean

no he's showing that you dont have to relearn the mappings since we can layer loom mappings on top of mojmaps if the issue is that you dont want to relearn all of the names of stuff

**Comment by MerpisMe** [comment]
> Krill issue

please shut the fuck up for a minute you can joke around after lol

**Comment by AViewFromTheTop** [comment]
> no he's showing that you dont have to relearn the mappings since we can layer loom mappings on top of mojmaps if the issue is that you dont want to relearn all of the names of stuff

oh then yeah i dont give the slightest shit, as long as it wont break registried for some reason

**Comment by Treetrain1** [comment]
> > no he's showing that you dont have to relearn the mappings since we can layer loom mappings on top of mojmaps if the issue is that you dont want to relearn all of the names of stuff
> 
> oh then yeah i dont give the slightest shit, as long as it wont break registried for some reason

it wont break registries

**Comment by AViewFromTheTop** [comment]
> it wont break registries

just trust me it did last time i tried it, even after running that stupid remap command

**Comment by MerpisMe** [comment]
we already have a branch for it and it works just fine

**Comment by BluePhoenixLOL** [comment]
Well its not now so we are committing. Sounds more like a gradle issue

**Comment by AViewFromTheTop** [comment]
why are you so mad

**Comment by MerpisMe** [comment]
> Well its not now so we are committing. Sounds more like a gradle issue

^^^
nine times out of ten when that sort of thing happens it's gradles fault lol

**Comment by MerpisMe** [comment]
> why are you so mad

who is

**Comment by AViewFromTheTop** [comment]
oh wait is it called yarn or loom mappings

**Comment by MerpisMe** [comment]
idk i think both maybe lol
