### ISSUE TITLE
IDEA: Rework the Warden's Sonic Boom

### ISSUE THREAD

**Issue by MerpisMe** [Soro335/WilderWild#98]
- The Warden shoots out a projectile similar to the Ancient Horn, but bigger
- This deals damage to multiple entities rather than just one
- Moves faster than the ancient horn projectile
- Also has flyby capabilities
- Still travels through blocks
- Emit a single sonic boom particle at the location of the warden so that it doesn't become completely unused

**PROS**
- Makes the attack potentially avoidable, but still deadly
- Deals damage to multiple entities, making it more difficult to spam golems around the warden
- More consistent with Ancient Horns

**CONS**
- Makes the attack potentially avoidable
- Might be difficult to implement
- Less precise

**Comment by MerpisMe** [comment]
this is just an idea btw, we totally dont have to do this

**Comment by BluePhoenixLOL** [comment]
ehhh nah

**Comment by AViewFromTheTop** [comment]
it's not more consistent with ancient horns- the warden creates an explosion of sound out of the shrieking of souls, the horn is just loud

**Comment by MerpisMe** [comment]
> it's not more consistent with ancient horns- the warden creates an explosion of sound out of the shrieking of souls, the horn is just loud

i mean in that case why doesn't activating a bunch of shriekers at once cause an ancient horn projectile to appear

but yeah if you guys dont want it then we dont need it
