### ISSUE TITLE
Incompatible with Simple Copper Pipes (resolved)

### ISSUE THREAD

**Issue by TheTrueTrident** [Soro335/WilderWild#99]
The occurs on both quilt and fabric (v1.0.5)
crash report below
![Screenshot 2022-08-19 184302](https://user-images.githubusercontent.com/79625988/185716555-abe96863-6c50-472c-983c-b6ae0716b309.png)

**Comment by Treetrain1** [comment]
It is incompatible with old versions. This mod has integration for Simple Copper Pipes 1.11 beta 4, so older versions will crash
